### ISSUE TITLE
"figure 3 - see dcc-methods/Results for paper/plotting"  - where is this in the repository?

### ISSUE THREAD

**Issue by ryanbadman** [akshey-kumar/BunDLe-Net#2]
Hello, for reproducing Fig 3 where is the script for that?

**Comment by akshey-kumar** [comment]
Hello! The plotting.py script was a bit outdated since the manuscript has gone through a number of version and consequently figure numbers have changed. Thanks for pointing that out! 

I have updated plotting.py to reflect the new figure numbers, with links to other repositories wherever necessary. To answer your question, the script for producing the plots in Figure 3 is now under the appropriate code section in plotting.py. The data for the plots was created in https://github.com/akshey-kumar/comparison-algorithms in scripts of the form <#_algorithm>.py

**Comment by akshey-kumar** [comment]
Hello! The plotting.py script was a bit outdated since the manuscript has gone through a number of version and consequently figure numbers have changed. Thanks for pointing that out! 

I have updated plotting.py to reflect the new figure numbers, with links to other repositories wherever necessary. To answer your question, the script for producing the plots in Figure 3 is now under the appropriate code section in plotting.py. The data for the plots was created in https://github.com/akshey-kumar/comparison-algorithms in scripts of the form <#_algorithm>.py

**Comment by akshey-kumar** [comment]
Hello! The `plotting.py` script was a bit outdated since the manuscript has gone through a number of versions, and consequently, the figure numbers have changed. Thanks for pointing that out! 

I have updated `plotting.py` to reflect the new figure numbers, with links to other repositories wherever necessary. To answer your question, the script for producing the plots in Figure 3 is now under the appropriate code section in `BunDLe-Net/scripts/plotting.py`. The data for the plots was created in https://github.com/akshey-kumar/comparison-algorithms in scripts of the form` <#_algorithm>.py`,
